/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * EmailActionConfig
 */

public class EmailActionConfig   {
  @SerializedName("title")
  private String title = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("columnName")
  private String columnName = null;

  @SerializedName("defaultValues")
  private Map<String, String> defaultValues = new HashMap<String, String>();

  @SerializedName("richText")
  private Boolean richText = false;

  public EmailActionConfig title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public EmailActionConfig content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public EmailActionConfig columnName(String columnName) {
    this.columnName = columnName;
    return this;
  }

   /**
   * Get columnName
   * @return columnName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColumnName() {
    return columnName;
  }

  public void setColumnName(String columnName) {
    this.columnName = columnName;
  }

  public EmailActionConfig defaultValues(Map<String, String> defaultValues) {
    this.defaultValues = defaultValues;
    return this;
  }

   /**
   * Get defaultValues
   * @return defaultValues
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getDefaultValues() {
    return defaultValues;
  }

  public void setDefaultValues(Map<String, String> defaultValues) {
    this.defaultValues = defaultValues;
  }

  public EmailActionConfig richText(Boolean richText) {
    this.richText = richText;
    return this;
  }

   /**
   * Get richText
   * @return richText
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getRichText() {
    return richText;
  }

  public void setRichText(Boolean richText) {
    this.richText = richText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailActionConfig emailActionConfig = (EmailActionConfig) o;
    return Objects.equals(this.title, emailActionConfig.title) &&
        Objects.equals(this.content, emailActionConfig.content) &&
        Objects.equals(this.columnName, emailActionConfig.columnName) &&
        Objects.equals(this.defaultValues, emailActionConfig.defaultValues) &&
        Objects.equals(this.richText, emailActionConfig.richText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, content, columnName, defaultValues, richText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailActionConfig {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    defaultValues: ").append(toIndentedString(defaultValues)).append("\n");
    sb.append("    richText: ").append(toIndentedString(richText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

