/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * OLAPTable
 */

public class OLAPTable   {
  @SerializedName("collections")
  private List<String> collections = new ArrayList<String>();

  @SerializedName("dimensions")
  private List<String> dimensions = new ArrayList<String>();

  /**
   * Gets or Sets aggregations
   */
  public enum AggregationsEnum {
    @SerializedName("COUNT")
    COUNT("COUNT"),
    
    @SerializedName("COUNT_UNIQUE")
    COUNT_UNIQUE("COUNT_UNIQUE"),
    
    @SerializedName("SUM")
    SUM("SUM"),
    
    @SerializedName("MINIMUM")
    MINIMUM("MINIMUM"),
    
    @SerializedName("MAXIMUM")
    MAXIMUM("MAXIMUM"),
    
    @SerializedName("AVERAGE")
    AVERAGE("AVERAGE"),
    
    @SerializedName("APPROXIMATE_UNIQUE")
    APPROXIMATE_UNIQUE("APPROXIMATE_UNIQUE");

    private String value;

    AggregationsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("aggregations")
  private List<AggregationsEnum> aggregations = new ArrayList<AggregationsEnum>();

  @SerializedName("measures")
  private List<String> measures = new ArrayList<String>();

  @SerializedName("tableName")
  private String tableName = null;

  public OLAPTable collections(List<String> collections) {
    this.collections = collections;
    return this;
  }

   /**
   * Get collections
   * @return collections
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<String> getCollections() {
    return collections;
  }

  public void setCollections(List<String> collections) {
    this.collections = collections;
  }

  public OLAPTable dimensions(List<String> dimensions) {
    this.dimensions = dimensions;
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<String> getDimensions() {
    return dimensions;
  }

  public void setDimensions(List<String> dimensions) {
    this.dimensions = dimensions;
  }

  public OLAPTable aggregations(List<AggregationsEnum> aggregations) {
    this.aggregations = aggregations;
    return this;
  }

   /**
   * Get aggregations
   * @return aggregations
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<AggregationsEnum> getAggregations() {
    return aggregations;
  }

  public void setAggregations(List<AggregationsEnum> aggregations) {
    this.aggregations = aggregations;
  }

  public OLAPTable measures(List<String> measures) {
    this.measures = measures;
    return this;
  }

   /**
   * Get measures
   * @return measures
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<String> getMeasures() {
    return measures;
  }

  public void setMeasures(List<String> measures) {
    this.measures = measures;
  }

  public OLAPTable tableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

   /**
   * Get tableName
   * @return tableName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OLAPTable oLAPTable = (OLAPTable) o;
    return Objects.equals(this.collections, oLAPTable.collections) &&
        Objects.equals(this.dimensions, oLAPTable.dimensions) &&
        Objects.equals(this.aggregations, oLAPTable.aggregations) &&
        Objects.equals(this.measures, oLAPTable.measures) &&
        Objects.equals(this.tableName, oLAPTable.tableName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collections, dimensions, aggregations, measures, tableName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OLAPTable {\n");
    
    sb.append("    collections: ").append(toIndentedString(collections)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    aggregations: ").append(toIndentedString(aggregations)).append("\n");
    sb.append("    measures: ").append(toIndentedString(measures)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

