/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * QueryError
 */

public class QueryError   {
  @SerializedName("message")
  private String message = null;

  @SerializedName("sqlState")
  private String sqlState = null;

  @SerializedName("errorCode")
  private Integer errorCode = null;

  @SerializedName("errorLine")
  private Integer errorLine = null;

  @SerializedName("charPositionInLine")
  private Integer charPositionInLine = null;

  public QueryError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public QueryError sqlState(String sqlState) {
    this.sqlState = sqlState;
    return this;
  }

   /**
   * Get sqlState
   * @return sqlState
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSqlState() {
    return sqlState;
  }

  public void setSqlState(String sqlState) {
    this.sqlState = sqlState;
  }

  public QueryError errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public QueryError errorLine(Integer errorLine) {
    this.errorLine = errorLine;
    return this;
  }

   /**
   * Get errorLine
   * @return errorLine
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getErrorLine() {
    return errorLine;
  }

  public void setErrorLine(Integer errorLine) {
    this.errorLine = errorLine;
  }

  public QueryError charPositionInLine(Integer charPositionInLine) {
    this.charPositionInLine = charPositionInLine;
    return this;
  }

   /**
   * Get charPositionInLine
   * @return charPositionInLine
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCharPositionInLine() {
    return charPositionInLine;
  }

  public void setCharPositionInLine(Integer charPositionInLine) {
    this.charPositionInLine = charPositionInLine;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryError queryError = (QueryError) o;
    return Objects.equals(this.message, queryError.message) &&
        Objects.equals(this.sqlState, queryError.sqlState) &&
        Objects.equals(this.errorCode, queryError.errorCode) &&
        Objects.equals(this.errorLine, queryError.errorLine) &&
        Objects.equals(this.charPositionInLine, queryError.charPositionInLine);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, sqlState, errorCode, errorLine, charPositionInLine);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryError {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    sqlState: ").append(toIndentedString(sqlState)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorLine: ").append(toIndentedString(errorLine)).append("\n");
    sb.append("    charPositionInLine: ").append(toIndentedString(charPositionInLine)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

