/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.rakam.client.model.QueryError;
import io.rakam.client.model.SchemaField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * QueryResult
 */

public class QueryResult   {
  @SerializedName("metadata")
  private List<SchemaField> metadata = new ArrayList<SchemaField>();

  @SerializedName("result")
  private List<List<Object>> result = new ArrayList<List<Object>>();

  @SerializedName("error")
  private QueryError error = null;

  @SerializedName("properties")
  private Map<String, Object> properties = new HashMap<String, Object>();

  @SerializedName("failed")
  private Boolean failed = false;

  public QueryResult metadata(List<SchemaField> metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<SchemaField> getMetadata() {
    return metadata;
  }

  public void setMetadata(List<SchemaField> metadata) {
    this.metadata = metadata;
  }

  public QueryResult result(List<List<Object>> result) {
    this.result = result;
    return this;
  }

   /**
   * Each row is an array that contains the values for the columns that are defined in metadata property.
   * @return result
  **/
  @ApiModelProperty(example = "null", value = "Each row is an array that contains the values for the columns that are defined in metadata property.")
  public List<List<Object>> getResult() {
    return result;
  }

  public void setResult(List<List<Object>> result) {
    this.result = result;
  }

  public QueryResult error(QueryError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public QueryError getError() {
    return error;
  }

  public void setError(QueryError error) {
    this.error = error;
  }

  public QueryResult properties(Map<String, Object> properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Map<String, Object> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Object> properties) {
    this.properties = properties;
  }

  public QueryResult failed(Boolean failed) {
    this.failed = failed;
    return this;
  }

   /**
   * Get failed
   * @return failed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFailed() {
    return failed;
  }

  public void setFailed(Boolean failed) {
    this.failed = failed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryResult queryResult = (QueryResult) o;
    return Objects.equals(this.metadata, queryResult.metadata) &&
        Objects.equals(this.result, queryResult.result) &&
        Objects.equals(this.error, queryResult.error) &&
        Objects.equals(this.properties, queryResult.properties) &&
        Objects.equals(this.failed, queryResult.failed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, result, error, properties, failed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryResult {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

