/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SchemaFieldInfo
 */

public class SchemaFieldInfo   {
  @SerializedName("category")
  private String category = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("STRING")
    STRING("STRING"),
    
    @SerializedName("INTEGER")
    INTEGER("INTEGER"),
    
    @SerializedName("DECIMAL")
    DECIMAL("DECIMAL"),
    
    @SerializedName("DOUBLE")
    DOUBLE("DOUBLE"),
    
    @SerializedName("LONG")
    LONG("LONG"),
    
    @SerializedName("BOOLEAN")
    BOOLEAN("BOOLEAN"),
    
    @SerializedName("DATE")
    DATE("DATE"),
    
    @SerializedName("TIME")
    TIME("TIME"),
    
    @SerializedName("TIMESTAMP")
    TIMESTAMP("TIMESTAMP"),
    
    @SerializedName("BINARY")
    BINARY("BINARY"),
    
    @SerializedName("ARRAY_STRING")
    ARRAY_STRING("ARRAY_STRING"),
    
    @SerializedName("ARRAY_INTEGER")
    ARRAY_INTEGER("ARRAY_INTEGER"),
    
    @SerializedName("ARRAY_DECIMAL")
    ARRAY_DECIMAL("ARRAY_DECIMAL"),
    
    @SerializedName("ARRAY_DOUBLE")
    ARRAY_DOUBLE("ARRAY_DOUBLE"),
    
    @SerializedName("ARRAY_LONG")
    ARRAY_LONG("ARRAY_LONG"),
    
    @SerializedName("ARRAY_BOOLEAN")
    ARRAY_BOOLEAN("ARRAY_BOOLEAN"),
    
    @SerializedName("ARRAY_DATE")
    ARRAY_DATE("ARRAY_DATE"),
    
    @SerializedName("ARRAY_TIME")
    ARRAY_TIME("ARRAY_TIME"),
    
    @SerializedName("ARRAY_TIMESTAMP")
    ARRAY_TIMESTAMP("ARRAY_TIMESTAMP"),
    
    @SerializedName("ARRAY_BINARY")
    ARRAY_BINARY("ARRAY_BINARY"),
    
    @SerializedName("MAP_STRING")
    MAP_STRING("MAP_STRING"),
    
    @SerializedName("MAP_INTEGER")
    MAP_INTEGER("MAP_INTEGER"),
    
    @SerializedName("MAP_DECIMAL")
    MAP_DECIMAL("MAP_DECIMAL"),
    
    @SerializedName("MAP_DOUBLE")
    MAP_DOUBLE("MAP_DOUBLE"),
    
    @SerializedName("MAP_LONG")
    MAP_LONG("MAP_LONG"),
    
    @SerializedName("MAP_BOOLEAN")
    MAP_BOOLEAN("MAP_BOOLEAN"),
    
    @SerializedName("MAP_DATE")
    MAP_DATE("MAP_DATE"),
    
    @SerializedName("MAP_TIME")
    MAP_TIME("MAP_TIME"),
    
    @SerializedName("MAP_TIMESTAMP")
    MAP_TIMESTAMP("MAP_TIMESTAMP"),
    
    @SerializedName("MAP_BINARY")
    MAP_BINARY("MAP_BINARY");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public SchemaFieldInfo category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public SchemaFieldInfo type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaFieldInfo schemaFieldInfo = (SchemaFieldInfo) o;
    return Objects.equals(this.category, schemaFieldInfo.category) &&
        Objects.equals(this.type, schemaFieldInfo.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaFieldInfo {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

