/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.api;

import io.rakam.ApiException;
import io.rakam.client.model.SuccessMessage;
import io.rakam.client.model.MaterializedView;
import io.rakam.client.model.ErrorMessage;
import io.rakam.client.model.MaterializedViewDeleteView;
import io.rakam.client.model.MaterializedViewSchema;
import io.rakam.client.model.MaterializedViewGetSchemaOfView;
import io.rakam.client.model.MaterializedViewGetView;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MaterializedviewApi
 */
public class MaterializedviewApiTest {

    private final MaterializedviewApi api = new MaterializedviewApi();

    
    /**
     * Create view
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createViewTest() throws ApiException {
        MaterializedView materializedView = null;
        // SuccessMessage response = api.createView(materializedView);

        // TODO: test validations
    }
    
    /**
     * Delete materialized view
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteViewTest() throws ApiException {
        MaterializedViewDeleteView materializedViewDeleteView = null;
        // SuccessMessage response = api.deleteView(materializedViewDeleteView);

        // TODO: test validations
    }
    
    /**
     * Get schemas
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchemaOfViewTest() throws ApiException {
        MaterializedViewGetSchemaOfView materializedViewGetSchemaOfView = null;
        // List<MaterializedViewSchema> response = api.getSchemaOfView(materializedViewGetSchemaOfView);

        // TODO: test validations
    }
    
    /**
     * Get view
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getViewTest() throws ApiException {
        MaterializedViewGetView materializedViewGetView = null;
        // MaterializedView response = api.getView(materializedViewGetView);

        // TODO: test validations
    }
    
    /**
     * List views
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listViewsTest() throws ApiException {
        // List<MaterializedView> response = api.listViews();

        // TODO: test validations
    }
    
}
