/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.api;

import io.rakam.ApiException;
import io.rakam.client.model.QueryResult;
import io.rakam.client.model.Execute;
import io.rakam.client.model.ErrorMessage;
import io.rakam.client.model.Explain;
import io.rakam.client.model.ResponseQuery;
import io.rakam.client.model.SchemaField;
import io.rakam.client.model.QueryMetadata;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QueryApi
 */
public class QueryApiTest {

    private final QueryApi api = new QueryApi();

    
    /**
     * Execute query on event data-set
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeTest() throws ApiException {
        Execute execute = null;
        // QueryResult response = api.execute(execute);

        // TODO: test validations
    }
    
    /**
     * Explain query
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void explainTest() throws ApiException {
        Explain explain = null;
        // ResponseQuery response = api.explain(explain);

        // TODO: test validations
    }
    
    /**
     * Test query
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void metadataTest() throws ApiException {
        QueryMetadata queryMetadata = null;
        // List<SchemaField> response = api.metadata(queryMetadata);

        // TODO: test validations
    }
    
}
