/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.api;

import io.rakam.ApiException;
import io.rakam.client.model.Recipe;
import io.rakam.client.model.ErrorMessage;
import io.rakam.client.model.SuccessMessage;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecipeApi
 */
public class RecipeApiTest {

    private final RecipeApi api = new RecipeApi();

    
    /**
     * Export recipe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exportRecipeTest() throws ApiException {
        String accept = null;
        // Recipe response = api.exportRecipe(accept);

        // TODO: test validations
    }
    
    /**
     * Install recipe
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void installRecipeTest() throws ApiException {
        // SuccessMessage response = api.installRecipe();

        // TODO: test validations
    }
    
}
