/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.api;

import io.rakam.ApiException;
import io.rakam.client.model.ErrorMessage;
import io.rakam.client.model.UserEmailActionBatch;
import io.rakam.client.model.UserEmailActionSend;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UseractionApi
 */
public class UseractionApiTest {

    private final UseractionApi api = new UseractionApi();

    
    /**
     * Apply batch operation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void batchTest() throws ApiException {
        UserEmailActionBatch userEmailActionBatch = null;
        // Long response = api.batch(userEmailActionBatch);

        // TODO: test validations
    }
    
    /**
     * Perform action for single user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendTest() throws ApiException {
        UserEmailActionSend userEmailActionSend = null;
        // Boolean response = api.send(userEmailActionSend);

        // TODO: test validations
    }
    
}
