/**
 * Rakam API Documentation
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.rakam.client.api;

import io.rakam.ApiCallback;
import io.rakam.ApiClient;
import io.rakam.ApiException;
import io.rakam.ApiResponse;
import io.rakam.Configuration;
import io.rakam.Pair;
import io.rakam.ProgressRequestBody;
import io.rakam.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;

import io.rakam.client.model.SuccessMessage;
import io.rakam.client.model.MaterializedView;
import io.rakam.client.model.ErrorMessage;
import io.rakam.client.model.MaterializedViewDeleteView;
import io.rakam.client.model.MaterializedViewSchema;
import io.rakam.client.model.MaterializedViewGetSchemaOfView;
import io.rakam.client.model.MaterializedViewGetView;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MaterializedviewApi {
    private ApiClient apiClient;

    public MaterializedviewApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MaterializedviewApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for createView */
    private com.squareup.okhttp.Call createViewCall(MaterializedView materializedView, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = materializedView;
        
        // verify the required parameter 'materializedView' is set
        if (materializedView == null) {
            throw new ApiException("Missing the required parameter 'materializedView' when calling createView(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/materialized-view/create".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "master_key" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * Create view
     * 
     * @param materializedView  (required)
     * @return SuccessMessage
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public SuccessMessage createView(MaterializedView materializedView) throws ApiException {
        ApiResponse<SuccessMessage> resp = createViewWithHttpInfo(materializedView);
        return resp.getData();
    }

    /**
     * Create view
     * 
     * @param materializedView  (required)
     * @return ApiResponse&lt;SuccessMessage&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<SuccessMessage> createViewWithHttpInfo(MaterializedView materializedView) throws ApiException {
        com.squareup.okhttp.Call call = createViewCall(materializedView, null, null);
        Type localVarReturnType = new TypeToken<SuccessMessage>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create view (asynchronously)
     * 
     * @param materializedView  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createViewAsync(MaterializedView materializedView, final ApiCallback<SuccessMessage> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createViewCall(materializedView, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<SuccessMessage>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for deleteView */
    private com.squareup.okhttp.Call deleteViewCall(MaterializedViewDeleteView materializedViewDeleteView, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = materializedViewDeleteView;
        
        // verify the required parameter 'materializedViewDeleteView' is set
        if (materializedViewDeleteView == null) {
            throw new ApiException("Missing the required parameter 'materializedViewDeleteView' when calling deleteView(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/materialized-view/delete".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "master_key" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * Delete materialized view
     * 
     * @param materializedViewDeleteView  (required)
     * @return SuccessMessage
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public SuccessMessage deleteView(MaterializedViewDeleteView materializedViewDeleteView) throws ApiException {
        ApiResponse<SuccessMessage> resp = deleteViewWithHttpInfo(materializedViewDeleteView);
        return resp.getData();
    }

    /**
     * Delete materialized view
     * 
     * @param materializedViewDeleteView  (required)
     * @return ApiResponse&lt;SuccessMessage&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<SuccessMessage> deleteViewWithHttpInfo(MaterializedViewDeleteView materializedViewDeleteView) throws ApiException {
        com.squareup.okhttp.Call call = deleteViewCall(materializedViewDeleteView, null, null);
        Type localVarReturnType = new TypeToken<SuccessMessage>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Delete materialized view (asynchronously)
     * 
     * @param materializedViewDeleteView  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteViewAsync(MaterializedViewDeleteView materializedViewDeleteView, final ApiCallback<SuccessMessage> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteViewCall(materializedViewDeleteView, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<SuccessMessage>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for getSchemaOfView */
    private com.squareup.okhttp.Call getSchemaOfViewCall(MaterializedViewGetSchemaOfView materializedViewGetSchemaOfView, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = materializedViewGetSchemaOfView;
        
        // verify the required parameter 'materializedViewGetSchemaOfView' is set
        if (materializedViewGetSchemaOfView == null) {
            throw new ApiException("Missing the required parameter 'materializedViewGetSchemaOfView' when calling getSchemaOfView(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/materialized-view/schema".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "read_key" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * Get schemas
     * 
     * @param materializedViewGetSchemaOfView  (required)
     * @return List&lt;MaterializedViewSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<MaterializedViewSchema> getSchemaOfView(MaterializedViewGetSchemaOfView materializedViewGetSchemaOfView) throws ApiException {
        ApiResponse<List<MaterializedViewSchema>> resp = getSchemaOfViewWithHttpInfo(materializedViewGetSchemaOfView);
        return resp.getData();
    }

    /**
     * Get schemas
     * 
     * @param materializedViewGetSchemaOfView  (required)
     * @return ApiResponse&lt;List&lt;MaterializedViewSchema&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<MaterializedViewSchema>> getSchemaOfViewWithHttpInfo(MaterializedViewGetSchemaOfView materializedViewGetSchemaOfView) throws ApiException {
        com.squareup.okhttp.Call call = getSchemaOfViewCall(materializedViewGetSchemaOfView, null, null);
        Type localVarReturnType = new TypeToken<List<MaterializedViewSchema>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get schemas (asynchronously)
     * 
     * @param materializedViewGetSchemaOfView  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getSchemaOfViewAsync(MaterializedViewGetSchemaOfView materializedViewGetSchemaOfView, final ApiCallback<List<MaterializedViewSchema>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getSchemaOfViewCall(materializedViewGetSchemaOfView, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<MaterializedViewSchema>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for getView */
    private com.squareup.okhttp.Call getViewCall(MaterializedViewGetView materializedViewGetView, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = materializedViewGetView;
        
        // verify the required parameter 'materializedViewGetView' is set
        if (materializedViewGetView == null) {
            throw new ApiException("Missing the required parameter 'materializedViewGetView' when calling getView(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/materialized-view/get".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "read_key" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * Get view
     * 
     * @param materializedViewGetView  (required)
     * @return MaterializedView
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public MaterializedView getView(MaterializedViewGetView materializedViewGetView) throws ApiException {
        ApiResponse<MaterializedView> resp = getViewWithHttpInfo(materializedViewGetView);
        return resp.getData();
    }

    /**
     * Get view
     * 
     * @param materializedViewGetView  (required)
     * @return ApiResponse&lt;MaterializedView&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<MaterializedView> getViewWithHttpInfo(MaterializedViewGetView materializedViewGetView) throws ApiException {
        com.squareup.okhttp.Call call = getViewCall(materializedViewGetView, null, null);
        Type localVarReturnType = new TypeToken<MaterializedView>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get view (asynchronously)
     * 
     * @param materializedViewGetView  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getViewAsync(MaterializedViewGetView materializedViewGetView, final ApiCallback<MaterializedView> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getViewCall(materializedViewGetView, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<MaterializedView>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for listViews */
    private com.squareup.okhttp.Call listViewsCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        

        // create path and map variables
        String localVarPath = "/materialized-view/list".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "read_key" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * List views
     * 
     * @return List&lt;MaterializedView&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<MaterializedView> listViews() throws ApiException {
        ApiResponse<List<MaterializedView>> resp = listViewsWithHttpInfo();
        return resp.getData();
    }

    /**
     * List views
     * 
     * @return ApiResponse&lt;List&lt;MaterializedView&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<MaterializedView>> listViewsWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = listViewsCall(null, null);
        Type localVarReturnType = new TypeToken<List<MaterializedView>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List views (asynchronously)
     * 
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listViewsAsync(final ApiCallback<List<MaterializedView>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listViewsCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<MaterializedView>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
